# Travis CI script

language: c

#   Build required projects first
before_script:

#   libsodium
- git clone git://github.com/jedisct1/libsodium.git
- ( cd libsodium; ./autogen.sh; ./configure; make check; sudo make install; sudo ldconfig )

#   Build and check this project
script:
- ./autogen.sh && ./configure --with-libsodium=yes && make && make check
- sudo make install
