# Travis CI script

language: c

os:
- linux
- osx

sudo: false
dist: trusty

addons:
  apt:
    sources:
    - sourceline: 'deb http://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-stable/xUbuntu_14.04/ ./'
      key_url: 'http://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-stable/xUbuntu_14.04/Release.key'
    packages:
    - libsodium-dev
    - asciidoc
    - xmlto

env:
 global:
  - DISTCHECK_CONFIGURE_FLAGS="--with-libsodium"

before_install:
- if [ $TRAVIS_OS_NAME == "osx" ] ; then brew install libsodium ; fi

# ZMQ stress tests need more open socket (files) than the usual default
# On OSX, it seems the way to set the max files limit is constantly changing, so
# try to use all known knobs to ensure compatibility across various versions
- if [ $TRAVIS_OS_NAME == "osx" ] ; then sudo sysctl -w kern.maxfiles=64000 ; sudo sysctl -w kern.maxfilesperproc=64000 ; sudo launchctl limit maxfiles 64000 64000 ; ulimit -n 64000 ; fi

#   Build and check this project
script:
- ./autogen.sh && ./configure --with-libsodium && make distcheck

# Deploy tags
before_deploy:
- . ./ci_deploy.sh
deploy:
  provider: releases
  api_key:
    secure: "C+hbVQQL62twHIit4vjExT908acpjQzxPvCgnKKVdEYm58+rXVvQ4HzOlNve7py522m/2iazwnJDX5bPskES5Kof3jqTJ2hZI9rcFXh1KuEjUojiPwix/mUnxFYcxS4PhgmyqG3z5YUsEXnDhwkOwsAVnQIJUFV1XAWMWwDCilI="
  file_glob: true
  file: ${ZEROMQ41_DEPLOYMENT}
  skip_cleanup: true
  on:
    repo: zeromq/zeromq4-1
    branch: master
    tags: true
    condition: "$TRAVIS_OS_NAME =~ (linux)"
